name: funk-word-map
services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - ${PORT_DB}:${PORT_DB}
    volumes:
      - /volumes/funk-word-map/${COOLIFY_ENVIRONMENT:-default}/pb_data:/pb/pb_data
    environment:
      PORT: ${PORT_DB}

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      target: production
    ports:
      - ${PORT_WEB}:${PORT_WEB}
    environment:
      ORIGIN: ${ORIGIN}
      PORT: ${PORT_WEB}
      DB_URL: ${DB_URL}
      DB_ADMIN_USER: ${DB_ADMIN_USER}
      DB_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD}
      ADMIN_AUTH: ${ADMIN_AUTH}

      PUBLIC_IS_STAGING: ${PUBLIC_IS_STAGING}
      PUBLIC_SOURCE_COMMIT: ${SOURCE_COMMIT}
      PUBLIC_ORIGIN: ${ORIGIN}
      PUBLIC_ENVIRONMENT: ${COOLIFY_ENVIRONMENT}

      PUBLIC_SENTRY_DSN_KEY: ${PUBLIC_SENTRY_DSN_KEY}
      PUBLIC_SENTRY_DSN_DOMAIN: ${PUBLIC_SENTRY_DSN_DOMAIN}
      PUBLIC_SENTRY_DSN_PROJECT_ID: ${PUBLIC_SENTRY_DSN_PROJECT_ID}
