name: funk-word-map
services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /pb/pb_data

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      target: production
    ports:
      - 80:80
