name: funk-word-map
services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./docker/db/volumes/pb_data:/pb/pb_data

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      target: dev
    ports:
      - 5173:5173
    volumes:
      - ./web:/work/web
      - ./data:/work/data
