name: funk-word-map
services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 5001:8080
    volumes:
      - /volumes/funk-word-map/staging/pb_data:/pb/pb_data
    # healthcheck:
    #   test: ["CMD", "curl", "-sSf", "http://localhost:8080"]
    #   interval: 1m
    #   timeout: 5s
    #   retries: 5
    #   start_period: 5s

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      target: production
    ports:
      - 5000:3000
    environment:
      ORIGIN:
      PORT: 3000
      DB_URL: http://db:5001
      DB_ADMIN_USER:
      DB_ADMIN_PASSWORD:
      PUBLIC_IS_STAGING:
    # healthcheck:
    #   test: ["CMD", "curl", "-sSf", "http://localhost:3000/api/health"]
    #   interval: 1m
    #   timeout: 5s
    #   retries: 5
    #   start_period: 5s
