name: funk-word-map
services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /volumes/funk-word-map/staging/pb_data:/pb/pb_data

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      target: production
    ports:
      - 3000:3000
    environment:
      ORIGIN:
      PORT: 3000
      DB_URL: http://db:8080
      DB_ADMIN_USER:
      DB_ADMIN_PASSWORD:
      PUBLIC_IS_STAGING:
